// Emits types/globals.d.ts and eslint/globals.cjs from the framework entries,
// so `import "UIKit"` leaves editors and linters knowing every ambient name.
var fs = require("fs")
var path = require("path")

var ROOT = path.join(__dirname, "..")
var FRAMEWORKS = {
    UIKit: "uikit",
    Foundation: "foundation",
    CoreAnimation: "coreanimation",
    AVKit: "avkit"
}

globalThis.$ = function() { return {} }

async function main() {
    var declarations = []
    var imports = []
    var globals = {}
    for (var framework of Object.keys(FRAMEWORKS)) {
        var directory = FRAMEWORKS[framework]
        var module = await import(path.join(ROOT, "src", directory, "index.js"))
        imports.push('import type * as ' + framework + ' from "./' + directory + '/index.js"')
        for (var name of Object.keys(module).sort()) {
            declarations.push("    const " + name + ": typeof " + framework + "." + name)
            if (_isClass(module[name])) {
                declarations.push("    type " + name + " = " + framework + "." + name)
            }
            globals[name] = "readonly"
        }
    }
    var dts = imports.join("\n") + "\n\n\n// Names made ambient by `import \"UIKit\"`, `import \"Foundation\"`, `import \"CoreAnimation\"` and `import \"AVKit\"`.\ndeclare global {\n" + declarations.join("\n") + "\n}\n\nexport {}\n"
    fs.mkdirSync(path.join(ROOT, "types"), {recursive: true})
    fs.writeFileSync(path.join(ROOT, "types", "globals.d.ts"), dts)
    fs.mkdirSync(path.join(ROOT, "eslint"), {recursive: true})
    fs.writeFileSync(path.join(ROOT, "eslint", "globals.cjs"), "// Generated by scripts/globals.cjs: the names `import \"UIKit\"` and friends make ambient, for eslint's `globals`.\nmodule.exports = " + JSON.stringify(globals, null, 4) + "\n")
    console.log("declared " + Object.keys(globals).length + " ambient names")
}

function _isClass(value) {
    return typeof value === "function" && /^class\s/.test(Function.prototype.toString.call(value))
}

main().catch(function(error) { console.error(error); process.exit(1) })
